#!/bin/bash

say -v "Anna" "ding ding ding" &
say -v "Bruce" "ding ding ding" &
say -v "Carmit" "ding ding ding" &
say -v "Fred" "ding ding ding" &
say -v "Junior" "ding ding ding" &
say -v "Karen" "ding ding ding" &
say -v "Kathy" "ding ding ding" &
say -v "Princess" "ding ding ding" &
say -v "Ralph" "ding ding ding" &
say -v "Vicki" "ding ding ding" &

printf "\a"
