#!/bin/bash

# set -ex

PHRASE="ding ding ding"

spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type male1 "$PHRASE"
sleep 1
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type male2 "$PHRASE"
sleep 1
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type male3 "$PHRASE"
exit
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type female1 "$PHRASE"
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type female2 "$PHRASE"
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type female3 "$PHRASE"
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type child_male "$PHRASE"
spd-say --rate "$(( RANDOM % 100 ))" --pitch "$(( ( RANDOM % 100 ) - $(( RANDOM % 100 )) ))" --voice-type child_female "$PHRASE"
