#!/bin/bash

set -e

DATETIME=`date -u +"%Y%m%d%H%M"`
#DATETIME=201810152015

ssh fbl.prod.web1.srobbins "
cd /var/www/vhosts/flashingblinkylights.com/current/
/home/srobbins/bin/magento-backup.sh -m db -o /home/srobbins/backup/ -n fbl.prod.magento.$DATETIME
"

scp fbl.prod.web1.srobbins:/home/srobbins/backup/fbl.prod.magento.$DATETIME.sql.gz /Users/steve/Project/fbl/db/fbl.prod.magento.$DATETIME.sql.gz

gzip -d /Users/steve/Project/fbl/db/fbl.prod.magento.$DATETIME.sql.gz

mysql -e "create database fbl_prod_magento_$DATETIME"

mysql fbl_prod_magento_$DATETIME < "/Users/steve/Project/fbl/db/fbl.prod.magento.$DATETIME.sql"

cd /Users/steve/html/fbl/

/Users/steve/bin/mage-local.py fbl "fbl_prod_magento_$DATETIME"
/Users/steve/bin/zettr apply srobbins app/etc/settings.csv

rsync -azv fbl.prod.web1.srobbins:/var/www/vhosts/flashingblinkylights.com/current/media/ media/ --exclude=cache --exclude=css --exclude=css_secure --exclude=js

gzip /Users/steve/Project/fbl/db/fbl.prod.magento.$DATETIME.sql

