#!/bin/bash

PROJECT_ROOT="/home/steve/html/hyperkin"

sed -i -e "s/true/false/g" "$PROJECT_ROOT/app/etc/modules/SFC_CimCore.xml"
sed -i -e "s/true/false/g" "$PROJECT_ROOT/app/etc/modules/Itoris_DynamicProductOptions.xml"
