#!/bin/bash

PDIR=/var/log/nginx

touch $PDIR/_ref.error.log

DIFF=`diff $PDIR/_ref.error.log $PDIR/error.log | grep 'FastCGI sent in stderr: "' | sed -e 's/^.*FastCGI sent in stderr: "//g'`

if [ ! -z "$DIFF" ]; then
#  say -r 300 -v Daniel "$DIFF" &
  notify-send -t 10000 -i face-surprise 'PHP Error' "$DIFF"
fi

cat $PDIR/error.log > $PDIR/_ref.error.log
